/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://maven.pkg.github.com/InstaCode/*")
    }
}

dependencies {
    implementation("io.rest-assured:rest-assured:4.4.0")
    implementation("org.springframework.cloud:spring-cloud-starter-config:1.1.3.RELEASE")
    implementation("org.springframework.cloud:spring-cloud-starter-eureka:1.1.7.RELEASE")
    implementation("io.zipkin.java:zipkin-server:1.16.2")
    implementation("junit:junit:4.13.2")
    implementation("io.rest-assured:rest-assured:4.4.0")
    runtimeOnly("io.zipkin.java:zipkin-autoconfigure-ui:1.16.2")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.5.2")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.5.2")
}

group = "io.instacode.automation"
version = "1.0-SNAPSHOT"
description = "InstaCode Microservices Tracing Server"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
